# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialSample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialSample

    pod 'Quikkly', :git => 'https://github.com/quikkly/ios-sdk.git'

end
